In [3]:
# Pandas is used to load, clean, and manipulate datasets
import pandas as pd

# NumPy is used for numerical operations and missing values
import numpy as np

In [4]:
# STEP 1: ADD THE 2025/2026 SEASON TO OUR EXISTING DATASET

# Load our original La Liga dataset (2014/15 to 2024/25)
laliga = pd.read_csv("laligamatches.csv")

# Load the new 2025/26 season
new_season = pd.read_csv("laliga_2025_2026.csv")

# Standardize column names to match our original dataset
new_season.columns = (
    new_season.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# Identify the season using its starting year
new_season["season"] = 2025

# Add missing columns and match the original column order
# Missing xG values will automatically become NaN
new_season = new_season.reindex(columns=laliga.columns)

# Replace any existing 2025/26 rows to avoid duplicates
laliga = laliga[laliga["season"] != 2025]

# Combine the original dataset with the new season
laliga_updated = pd.concat(
    [laliga, new_season],
    ignore_index=True
)

# Verify that we have 20 teams for the new season
assert len(new_season) == 20, "Expected 20 teams for 2025/26"

# Verify that no season/team combination is duplicated
assert not laliga_updated.duplicated(
    subset=["season", "squad"]
).any(), "Duplicate season/team detected"

# Save the updated dataset back to our original CSV
laliga_updated.to_csv("laligamatches.csv", index=False)

# Display the results
print("Dataset successfully updated!")
print("Total rows and columns:", laliga_updated.shape)
print("Number of seasons:", laliga_updated["season"].nunique())

# Display the newly added season
display(laliga_updated[laliga_updated["season"] == 2025].head())

Dataset successfully updated!
Total rows and columns: (240, 20)
Number of seasons: 12

,rk,squad,mp,w,d,l,gf,ga,gd,pts,pts/mp,attendance,top_team_scorer,goalkeeper,notes,season,xg,xga,xgd,xgd/90
220,1,Barcelona,38,31,1,6,95,36,59,94,2.47,45099.0,Ferran Torres Lamine Yamal - 16,Joan García,→ Champions League via league finish,2025,NaN,NaN,NaN,NaN
221,2,Real Madrid,38,27,5,6,77,35,42,86,2.26,71549.0,Kylian Mbappé - 25,Thibaut Courtois,→ Champions League via league finish,2025,NaN,NaN,NaN,NaN
222,3,Villarreal,38,22,6,10,72,46,26,72,1.89,17989.0,Georges Mikautadze - 13,Luiz Lúcio Reis Júnior,→ Champions League via league finish,2025,NaN,NaN,NaN,NaN
223,4,Atlético Madrid,38,21,6,11,62,44,18,69,1.82,60855.0,Alexander Sørloth - 13,Jan Oblak,→ Champions League via league finish,2025,NaN,NaN,NaN,NaN
224,5,Real Betis,38,15,15,8,59,48,11,60,1.58,57427.0,Cucho - 11,Álvaro Vallés,→ Champions League via league finish,2025,NaN,NaN,NaN,NaN

In [5]:
# Display all columns when viewing DataFrames
pd.set_option("display.max_columns", None)

In [6]:
# Inspect our combined dataset

# Load the combined La Liga dataset
laliga = pd.read_csv("laligamatches.csv")

# Display the dataset dimensions
print("Dataset shape:", laliga.shape)

# Display information about each column
# This includes data types and non-null values
print("\nDataset information:")
laliga.info()

# Count missing values in each column
print("\nMissing values per column:")
print(laliga.isnull().sum())

# Display the first five rows
display(laliga.head())

Dataset shape: (240, 20)

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rk               240 non-null    int64
 1   squad            240 non-null    object
 2   mp               240 non-null    int64
 3   w                240 non-null    int64
 4   d                240 non-null    int64
 5   l                240 non-null    int64
 6   gf               240 non-null    int64
 7   ga               240 non-null    int64
 8   gd               240 non-null    int64
 9   pts              240 non-null    int64
 10  pts/mp           240 non-null    float64
 11  attendance       224 non-null    float64
 12  top_team_scorer  240 non-null    object
 13  goalkeeper       240 non-null    object
 14  notes            122 non-null    object
 15  season           240 non-null    int64
 16  xg               160 non-null    float64
 17  xga              160 non-null    float64
 18  xgd              160 non-null    float64
 19  xgd/90           160 non-null    float64
dtypes: float64(6), int64(10), object(4)
memory usage: 37.6+ KB

Missing values per column:
rk                   0
squad                0
mp                   0
w                    0
d                    0
l                    0
gf                   0
ga                   0
gd                   0
pts                  0
pts/mp               0
attendance          16
top_team_scorer      0
goalkeeper           0
notes              118
season               0
xg                  80
xga                 80
xgd                 80
xgd/90              80
dtype: int64

,rk,squad,mp,w,d,l,gf,ga,gd,pts,pts/mp,attendance,top_team_scorer,goalkeeper,notes,season,xg,xga,xgd,xgd/90
0,1,Barcelona,38,30,4,4,110,21,89,94,2.47,77632.0,Lionel Messi - 43,Claudio Bravo,→ Champions League via Champions League win,2014,NaN,NaN,NaN,NaN
1,2,Real Madrid,38,30,2,6,118,38,80,92,2.42,73545.0,Cristiano Ronaldo - 48,Iker Casillas,→ Champions League via league finish,2014,NaN,NaN,NaN,NaN
2,3,Atlético Madrid,38,23,9,6,67,29,38,78,2.05,46454.0,Antoine Griezmann - 22,Miguel Ángel Moyá,→ Champions League via league finish,2014,NaN,NaN,NaN,NaN
3,4,Valencia,38,22,11,5,70,32,38,77,2.03,43125.0,Daniel Parejo - 12,Diego Alves,→ Champions League via league finish,2014,NaN,NaN,NaN,NaN
4,5,Sevilla,38,23,7,8,71,45,26,76,2.00,30878.0,Carlos Bacca - 20,Sergio Rico,→ Champions League via Europa League win,2014,NaN,NaN,NaN,NaN

In [7]:
# STEP 3: CHECK MISSING VALUES BY SEASON

# Group the dataset by season
# Count how many missing values each season has
missing_by_season = (
    laliga.groupby("season")
    [["attendance", "xg", "xga", "xgd", "xgd/90"]]
    .apply(lambda group: group.isnull().sum())
)

# Display the results
display(missing_by_season)

        attendance  xg  xga  xgd  xgd/90
season
2014             0  20   20   20      20
2015             0  20   20   20      20
2016             0  20   20   20      20
2017             0   0    0    0       0
2018             0   0    0    0       0
2019             0   0    0    0       0
2020            16   0    0    0       0
2021             0   0    0    0       0
2022             0   0    0    0       0
2023             0   0    0    0       0
2024             0   0    0    0       0
2025             0  20   20   20      20

In [8]:
# STEP 4: VALIDATE OUR FOOTBALL STATISTICS

# Check that wins + draws + losses = matches played
invalid_matches = laliga[
    laliga["w"] + laliga["d"] + laliga["l"] != laliga["mp"]
]

# Check that goals for - goals against = goal difference
invalid_goal_difference = laliga[
    laliga["gf"] - laliga["ga"] != laliga["gd"]
]

# Check that points = 3 * wins + draws
invalid_points = laliga[
    3 * laliga["w"] + laliga["d"] != laliga["pts"]
]

# Check for duplicate teams within the same season
duplicates = laliga[
    laliga.duplicated(subset=["season", "squad"], keep=False)
]

# Display validation results
print("Invalid match totals:", len(invalid_matches))
print("Invalid goal differences:", len(invalid_goal_difference))
print("Invalid point totals:", len(invalid_points))
print("Duplicate team-season records:", len(duplicates))

Invalid match totals: 0
Invalid goal differences: 0
Invalid point totals: 1
Duplicate team-season records: 0

In [9]:
# STEP 5: INVESTIGATE INVALID POINT TOTALS

# Display the team whose points don't match
# the standard football points formula
display(
    invalid_points[
        ["season", "squad", "mp", "w", "d", "l", "pts", "notes"]
    ]
)

# Calculate how many points the team should have
# based on its wins and draws
invalid_points = invalid_points.copy()

invalid_points["expected_pts"] = (
    3 * invalid_points["w"] + invalid_points["d"]
)

# Calculate the difference between actual and expected points
invalid_points["difference"] = (
    invalid_points["pts"] - invalid_points["expected_pts"]
)

# Display the comparison
display(
    invalid_points[
        ["season", "squad", "pts", "expected_pts", "difference"]
    ]
)

    season    squad  mp  w  d   l  pts                           notes
18    2014  Almería  38  8  8  22   29  3-point deduction 4, Relegated

    season    squad  pts  expected_pts  difference
18    2014  Almería   29            32          -3

In [10]:
# STEP 6: SAVE OUR CLEANED DATASET

# Create a separate copy of our validated dataset
# This preserves the original DataFrame
laliga_cleaned = laliga.copy()

# Sort teams chronologically by season and league position
laliga_cleaned = laliga_cleaned.sort_values(
    by=["season", "rk"]
).reset_index(drop=True)

# Save the cleaned dataset to a new CSV file
# index=False prevents pandas from adding an extra index column
laliga_cleaned.to_csv("laliga_cleaned.csv", index=False)

# Verify that the file was saved correctly
print("Cleaned dataset saved successfully!")
print("Dataset shape:", laliga_cleaned.shape)
print("Seasons:", laliga_cleaned["season"].nunique())

# Display the last five rows
display(laliga_cleaned.tail())

Cleaned dataset saved successfully!
Dataset shape: (240, 20)
Seasons: 12

,rk,squad,mp,w,d,l,gf,ga,gd,pts,pts/mp,attendance,top_team_scorer,goalkeeper,notes,season,xg,xga,xgd,xgd/90
235,16,Levante,38,11,9,18,47,61,-14,42,1.11,20211.0,Carlos Espí - 11,Mathew Ryan,NaN,2025,NaN,NaN,NaN,NaN
236,17,Osasuna,38,11,9,18,44,50,-6,42,1.11,20560.0,Ante Budimir - 17,Sergio Herrera,NaN,2025,NaN,NaN,NaN,NaN
237,18,Mallorca,38,11,9,18,47,57,-10,42,1.11,17737.0,Vedat Muriqi - 23,Leo Román,Relegated,2025,NaN,NaN,NaN,NaN
238,19,Girona,38,9,14,15,39,55,-16,41,1.08,11931.0,Vladyslav Vanat - 9,Paulo Gazzaniga,Relegated,2025,NaN,NaN,NaN,NaN
239,20,Oviedo,38,6,11,21,26,60,-34,29,0.76,24888.0,Federico Viñas - 9,Aarón Escandell,Relegated,2025,NaN,NaN,NaN,NaN

In [11]:
# STEP 7: INSPECT TEAM NAME CONSISTENCY

# Display all unique team names in alphabetical order
team_names = sorted(laliga_cleaned["squad"].unique())

print("Number of unique team names:", len(team_names))

# Display the team names
for team in team_names:
    print(team)

Number of unique team names: 33
Alavés
Almería
Athletic Club
Atlético Madrid
Barcelona
Betis
Celta Vigo
Cádiz
Córdoba
Eibar
Elche
Espanyol
Getafe
Girona
Granada
Huesca
La Coruña
Las Palmas
Leganés
Levante
Mallorca
Málaga
Osasuna
Oviedo
Rayo Vallecano
Real Betis
Real Madrid
Real Sociedad
Sevilla
Sporting Gijón
Valencia
Valladolid
Villarreal

In [12]:
# STEP 8: STANDARDIZE TEAM NAMES

# Create a dictionary mapping inconsistent names
# to a single standardized team name
team_name_mapping = {
    "Real Betis": "Betis"
}

# Replace inconsistent team names
laliga_cleaned["squad"] = (
    laliga_cleaned["squad"].replace(team_name_mapping)
)

# Check the number of unique teams
print("Unique teams:", laliga_cleaned["squad"].nunique())

# Verify that Real Betis is now consistently named Betis
display(
    laliga_cleaned[
        laliga_cleaned["squad"] == "Betis"
    ][["season", "squad", "pts"]]
    .sort_values("season")
)

# Check for duplicate team-season records
print(
    "Duplicate records:",
    laliga_cleaned.duplicated(
        subset=["season", "squad"]
    ).sum()
)

Unique teams: 32

     season  squad  pts
29     2015  Betis   45
54     2016  Betis   39
65     2017  Betis   60
89     2018  Betis   50
114    2019  Betis   41
125    2020  Betis   61
144    2021  Betis   65
165    2022  Betis   60
186    2023  Betis   57
205    2024  Betis   60
224    2025  Betis   60

Duplicate records: 0

In [14]:
# STEP 9: SAVE CORRECTED DATASET

# Save the updated cleaned dataset
# without modifying the original raw CSV
laliga_cleaned.to_csv(
    "../LinearRegression/laliga_cleaned.csv",
    index=False
)

print("Corrected dataset saved successfully!")
print("Dataset shape:", laliga_cleaned.shape)

Corrected dataset saved successfully!
Dataset shape: (240, 20)